### ISSUE TITLE
Picker claims Firefox 114.0b9 does not support P3 when it does

### ISSUE THREAD

**Issue by thonkinator** [evilmartians/oklch-picker#122] opened 2023-06-01 23:28 UTC
Exactly what the title says. When selecting a P3-only color in the picker, I get the "P3 is unavailable in this browser" fallback notice. However, Firefox has supported P3 since 113, so I don't know why I'm getting this. I am on Firefox Developer Edition, but I don't know if that would change anything.

**Comment by ai** [comment] 2023-06-01 23:31
Any proofs of adding a support?

**Comment by thonkinator** [comment] 2023-06-02 00:01
@ai [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch#browser_compatibility) and [CanIUse](https://caniuse.com/mdn-css_types_color_oklch) both show that compatibility was added to Firefox in 113. I've also tested myself and the OKLCH function and fallback color I got from the color picker are different colors.

**Comment by thonkinator** [comment] 2023-06-02 00:05
The reason for this would seem to be [this line](https://github.com/evilmartians/oklch-picker/blob/a95647ef0a5ab8e9b107263190357c3125066f86/stores/support.ts#L17) that explicitly removes support for Firefox. [This bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1626624) that the comment above links to is still open, but as you can see at the bottom of the page, it is a duplicate of (https://bugzilla.mozilla.org/show_bug.cgi?id=1830268)[another bug], which _is_ closed.

**Comment by ai** [comment] 2023-06-02 08:48
As I know `oklch()` in Firefox was implemented without P3 support.

Gamut mapping mentioned in the issue is not a P3 support.

Can you open FF on P3 compatible hardware (Apple is recommended) and proof that it is render P3? (I tested it a few versions ago and it didn't work).

**Comment by tylermumford** [comment] 2023-06-07 04:14
Hello. I picked a color in P3 space (`oklch(36.03% 0.111 153)`) and set it to a page's background color. I then created two paragraphs: the first colored in oklch.com's fallback color (`#004b24`) and the second colored in the oklch P3 color (same as background).

I can just barely see the text that's set in the fallback color. I cannot see the text that's set in the same color as the background. This indicates to me that Firefox supports P3 colors. Right?

Firefox 113.0.2 (64-bit), on a 2022 MacBook Air

<img width="850" alt="image" src="https://github.com/evilmartians/oklch-picker/assets/531333/8508aba0-ebac-4a38-a3cd-bc76a4bf4193">

**Comment by ai** [comment] 2023-06-07 07:24
No, it should be opposite.

P3 support means that browser will show P3 color on P3 capable hardware.

Showing sRGB fallback (on P3 capable monitor) means that browsers doesn't have P3 support.

**Comment by ai** [comment] 2023-09-25 21:33
I close this issue since FF has no P3 support

**Closed by ai** 2023-09-25 21:33 UTC

**Comment by TheCommieAxolotl** [comment] 2024-01-17 01:29
@ai FF 121.0.1 on a 2021 Mac with p3 enabled, doing the test above yielded these results:

<img width="1365" alt="Screenshot 2024-01-17 at 12 18 52 pm" src="https://github.com/evilmartians/oklch-picker/assets/87679354/d54a65c3-7225-4c22-a65b-8b678ab93795">
<img width="756" alt="Screenshot 2024-01-17 at 12 18 56 pm" src="https://github.com/evilmartians/oklch-picker/assets/87679354/25662210-b19b-404a-8718-9e598a0a17a1">

If i'm not mistaken, this shows me that FF now does have p3 support, as the fallback color is not being used by the background. If i'm wrong about what should be showing please correct me.

<img width="403" alt="Screenshot 2024-01-17 at 12 24 07 pm" src="https://github.com/evilmartians/oklch-picker/assets/87679354/9e1fb48e-7872-4b42-83a8-81be743ac659">

(done in firefox, manually overriding the "Browser does not support x" to show the oklch color)

**Comment by TheCommieAxolotl** [comment] 2024-01-17 01:36
Also, even if the [bugzilla entry](https://bugzilla.mozilla.org/show_bug.cgi?id=1626624) isn't closed, is there harm in keeping the comment but removing the `isFF` check? showing the p3 preview, even if slightly inaccurate seems favourable to me than preventing it from showing.

**Comment by ai** [comment] 2024-01-17 17:58
Sure. Done b834c95

Thanks for screenshots are arguments.

**Comment by TheCommieAxolotl** [comment] 2024-01-17 23:03
Thank you!
